### ISSUE TITLE
Fehlende 'Bootstrap Navigation Classes' Ausgabe 

### ISSUE THREAD

**Issue by RoflCopter24** [contao-bootstrap/navbar#12]
Moin!

Kleine Fehlerkorrektur:
Das im Backendmodul `Navigationsmenü` ausfüllbare Feld `Bootstrap Navigation Classes` wird nicht ausgegeben.

In src/Helper/NavigationHelper.php nach Zeile 72 fehlt:
```php
$attributes->addClass($this->template->navClass);
```
Dann flutscht das :-)

**Comment by dmolineus** [comment]
Ja, das ist verwirrend und der Modularisierung geschuldet. Die Funktion stammt von **contao-bootstrap/templates** und wird im Template `nav_bs` berücksichtigt. Ist **contao-bootstrap/templates** nicht installiert, gibt es das Feld nicht.

Ich werde voraussichtlich den Support wie vorgeschlagen einbauen. Wenn die Template-Komponente nicht installiert ist, sollten ja keine Probleme auftreten.

**Comment by dmolineus** [comment]
Implemented with ef1beaf.
