### ISSUE TITLE
B4 Beta

### ISSUE THREAD

**Issue by swinde** [contao-bootstrap/navbar#4]
In der Beta version wird aus
$cssID[1] = trim($cssID[1] . ' navbar-toggleable-' . $this->bs_toggleableSize);
wieder
$cssID[1] = trim($cssID[1] . ' navbar-expand-' . $this->bs_toggleableSize);

**Comment by wiphi** [comment]
Und aus `$cssID[1] = 'navbar-light bg-faded';` wird `$cssID[1] = 'navbar-light bg-light';`

**Comment by dmolineus** [comment]
Fixed with fc11627e29e342cef360cc89d62f4f9c040b61a5.
