### ISSUE TITLE
Navigationsleiste (Bootstrap) Chrome

### ISSUE THREAD

**Issue by cgpro** [contao-bootstrap/navbar#5]
Im Bereich "Module" kann in Google Chrome kein weiteres Modul hinzugefügt werden. Im Firefox klappts.

**Comment by cgpro** [comment]
Und eine Kleinigkeit noch, wenn das Backendlayout auf "Breite begrenzen" gestellt ist, ragen die Felder aus dem Layout, sieht man auch wenn man die Breite nicht begrenzt hat und das Fenster schmäler zieht. Ich meine damit die Felder "Template für Header-Titel" und "Module".

**Comment by dmolineus** [comment]
Am multicolumnwizad wurde in den letzter Zeit einiges herum gepfuscht. Unter anderem  Js-Changes. Strg+f5 sollte helfen.

**Comment by cgpro** [comment]
Nach dem Cache leeren passts im Firefox auch nicht mehr hehe. Ist in beiden Browsern "überstehend". Liegt aber dann am multicolumnwizard, right?

**Comment by dmolineus** [comment]
Ich vermute dass es am mcw liegt. Ggf. Mal auf den 3.3.10 zurückgehen.

Das Styling ist noch verbesserungswürdig. 

Der mcw kommt nicht mit Contao 4 klar. Da muss ein custom style ran.

**Comment by cgpro** [comment]
Ok, hoffe mein Bugreport war ausreichend um es nachvollziehen zu können :)

**Comment by dmolineus** [comment]
Probleme mit der Breite werden mit 82cc4463e0d4403e8a93a03a1f6e9ed9d478f4c6 behoben sein.

**Comment by cgpro** [comment]
Cool danke! :)
