### ISSUE TITLE
Es kann nur ein Modul hinzugefügt werden

### ISSUE THREAD

**Issue by nrunde** [contao-bootstrap/navbar#7]
In den Moduleinstellungen scheint das Multicolumnwizard JS nicht korrekt zu funktionieren. Es wir kein weiteres Modul Select Feld erstellt wenn ich auf die "Plus"-Icons klicke.

![image](https://user-images.githubusercontent.com/1148170/32941239-64fd2462-cb85-11e7-88bb-38d1b8e8458e.png)

Contao läuft in Version 4.4.8

**Comment by dmolineus** [comment]
Welche Version des mcw ist installiert? Version 3.3.11-3.3.13 waren defekt. Ggf. Browsercache leeren.

**Comment by nrunde** [comment]
MCW V 3.3.14 mit Contao Update eingespielt und Cache gelöscht - läuft wieder. Danke!
